INSERT INTO USER_TABLE VALUES (0, 'HELLO', 'WORLD');
INSERT INTO ARTICLE (ID, TITLE, BODY, USER_ID, CREATED_DATE, LAST_MODIFIED) VALUES (0, 'HELLO', 'WORLD', 0, NOW(), NULL);
INSERT INTO ARTICLE (ID, TITLE, BODY, USER_ID, CREATED_DATE, LAST_MODIFIED) VALUES (-1, 'HELLO2', 'WORLD2', 0, NOW(), NULL);
--INSERT INTO USER_AUTHORITIES VALUES (0, 1)