INSERT INTO USER_TABLE (ID, USERNAME, PASSWORD) VALUES (0, 'test', 'test123');
INSERT INTO ARTICLE (ID, TITLE, BODY, USER_ID, CREATED_DATE, LAST_MODIFIED) VALUES (0, 'HELLO', 'WORLD', 0, NOW(), NULL);
INSERT INTO ARTICLE (ID, TITLE, BODY, USER_ID, CREATED_DATE, LAST_MODIFIED) VALUES (-1, 'HELLO2', 'WORLD2', 0, NOW(), NULL);
--INSERT INTO USER_AUTHORITIES VALUES (0, 1)